version: '2' # composeファイルバージョン
services:
  # 必要なのはPHP(+Apache)サービス用のコンテナのみ
  php:
    build: ./php # php/Dockerfileからビルド
    ports:
      # ホストとPHPコンテナのポートをつなぐための設定
      - 80:80
    volumes:
      # ホストの ./html とゲスト(PHPコンテナ)の /var/www/html をつなぐ
      # => Windows側からPHPコンテナのドキュメントルートにアクセス可
      - ./html:/var/www/html
    environment:
      VIRTUAL_HOST: example.com