version: '2' # composeファイルバージョン
services:
  # 必要なのはPHP(+Apache)サービス用のコンテナのみ
  php:
    build: ./php # php/Dockerfileからビルド
    container_name: php-apache # コンテナ名を"php-apache"に
    ports:
      - '80:80' # ホスト80番ポートとゲスト(PHPコンテナ)80番ポートをつなぐ
    volumes:
      # ホストの ./html とゲスト(PHPコンテナ)の /var/www/html をつなぐ
      # => ホスト側からPHPコンテナのドキュメントルートにアクセス可
      - ./html:/var/www/html
