version: "3"

services:
  # client サービスコンテナ
  client:
    image: busybox
    # ログ出力フォーマット: 基本的に json-file で良い
    logging:
      driver: json-file
    # ターミナルを利用可能に
    tty: true
    # デフォルト bridge ネットワークに所属
    network_mode: bridge
