version: '2' # composeファイルバージョン
services:
  # 必要なのはPHP(+Apache)サービス用のコンテナのみ
  php:
    build: ./php # php/Dockerfileからビルド
    ports:
      # ホストとPHPコンテナのポートをつなぐための設定
      # ポート8000と8001を使用するため、以下のように設定する
      # ※範囲指定で '8000-8001:8000-8001' と1行で記述することも可能
      - '8000:8000'
      - '8001:8001'
    volumes:
      # ホストの ./html とゲスト(PHPコンテナ)の /var/www/html をつなぐ
      # => Windows側からPHPコンテナのドキュメントルートにアクセス可
      - ./html:/var/www/html