version: "3"

# 作成する仮想ネットワークを定義
networks:
  # app_net 仮想ネットワーク
  app_net:
    driver: bridge # ドライバは基本的に bridge を指定
    ipam:
     driver: default
     config:
       # 仮想ネットワークのネットワーク範囲を指定
       ## 178.27.0.0/16 の場合、178.27.0.1 ～ 178.27.255.254 のIPアドレスを割り振れる
       ## ただし 178.27.0.1 はゲートウェイに使われる
       - subnet: 178.27.0.0/16

services:
  # server サービスコンテナ
  server:
    image: busybox
    # ログ出力フォーマット: 基本的に json-file で良い
    logging:
      driver: json-file
    # ターミナルを利用可能に
    tty: true
    # app_net ネットワークに所属
    ## IP指定した場合はサービス名による名前解決はできない
    networks:
      app_net:
        # 178.27.0.0/16 のネットワーク範囲で任意のIPアドレスを設定できる
        ipv4_address: 178.27.0.10
  
  # client サービスコンテナ
  client:
    image: busybox
    # ログ出力フォーマット: 基本的に json-file で良い
    logging:
      driver: json-file
    # ターミナルを利用可能に
    tty: true
    # app_net ネットワークに所属
    ## IP指定した場合はサービス名による名前解決はできない
    networks:
      app_net:
        # 178.27.0.0/16 のネットワーク範囲で任意のIPアドレスを設定できる
        ipv4_address: 178.27.0.20
