version: "3"

services:
  # web サービスコンテナ
  web:
    image: nginx:alpine
    # ログ出力フォーマット: 基本的に json-file で良い
    logging:
      driver: json-file
    # localhost 上で稼働
    ## http://localhost = http://localhost:80 = service://web:80
    network_mode: host
    # ボリュームマウント
    volumes:
      # host:./index.html => service://web:/usr/share/nginx/html/index.html
      - ./index.html:/usr/share/nginx/html/index.html
