version: "3" # composeファイルバージョン指定

# 各種コンテナの定義
services:
  # webサービス: php:7.4-apache イメージから構築
  ## コンテナ名: training2_web
  web:
    # ./docker/web/Dockerfile をビルド
    build: ./docker/web/
    container_name: training2_web
    # ログ出力フォーマット: 基本的に json-file で良い
    logging:
      driver: json-file
    ports:
      - "80:80" # http://localhost:80 => service://web:80
    links:
      - db # dbサービス（training2_dbコンテナ）とリンク
           ## これにより tcp://db:3306 => service://db:3306 の接続が可能になる
  
  # dbサービス: mysql:5.7 イメージから構築
  ## コンテナ名: training2_db
  db:
    # ./docker/db/Dockerfile をビルド
    build: ./docker/db/
    container_name: training2_db
    # ログ出力フォーマット: 基本的に json-file で良い
    logging:
      driver: json-file
    # 環境変数定義
    environment:
      # MySQL rootユーザパスワードを指定しないとMySQLのDockerコンテナは起動しない
      MYSQL_ROOT_PASSWORD: root
